### ISSUE TITLE
Error on git hash when trying to build the project

### ISSUE THREAD

**Issue by vicentematus** [DethRaid/wad2gltf#4]
Running this on a `Mac M1 Pro`, whenever i try to run the build command on the root directory with:

`cmake .`

It throws the following output:
```bash

[ 11%] Performing download step (git clone) for 'fastgltf-populate'
Cloning into 'fastgltf-src'...
fatal: reference is not a tree: 8e6556746016e0309e02f013d3a3ebd8c0a53856
CMake Error at fastgltf-subbuild/fastgltf-populate-prefix/tmp/fastgltf-populate-gitclone.cmake:49 (message):
  Failed to checkout tag: '8e6556746016e0309e02f013d3a3ebd8c0a53856'


make[2]: *** [fastgltf-populate-prefix/src/fastgltf-populate-stamp/fastgltf-populate-download] Error 1
make[1]: *** [CMakeFiles/fastgltf-populate.dir/all] Error 2
make: *** [all] Error 2

CMake Error at /opt/homebrew/Cellar/cmake/3.28.2/share/cmake/Modules/FetchContent.cmake:1679 (message):
  Build step for fastgltf failed: 2
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.28.2/share/cmake/Modules/FetchContent.cmake:1819:EVAL:2 (__FetchContent_directPopulate)
  /opt/homebrew/Cellar/cmake/3.28.2/share/cmake/Modules/FetchContent.cmake:1819 (cmake_language)
  /opt/homebrew/Cellar/cmake/3.28.2/share/cmake/Modules/FetchContent.cmake:2033 (FetchContent_Populate)
  wad2gltf/CMakeLists.txt:32 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
```  

It seems that the git hash doesnt exist on the fastglf repository, so that's why its failing. I tried cloning the repository and checking the hash and it failed.

https://github.com/DethRaid/wad2gltf/blob/b263853dec596d63a28eee4c68024e8f5ffa66c4/wad2gltf/CMakeLists.txt#L20-L24

If you need more system specs i can send you more info. Thanks.

**Comment by DethRaid** [comment]
`wad2gltf` is using a commit from a branch of `fastgltf` to get support for exporting glTF files. The `fastgltf` author force-pushed to that branch, removing the commit `wad2gltf` used

However, the `fastgltf` branch I was using has been merged into `main`. I'm working on updating `fastgltf` to `main`, keep an eye out for the next commit

**Comment by DethRaid** [comment]
Should be fixed as of c13c670d275ec7230efd1cfcdef6792892678958

**Comment by vicentematus** [comment]
Thanks for the fix. Plus true force-pushing with `rebase` or `fixup` can mess up with git history. 

Do you have a guide any guide for the build steps? It throwing some compilation errors with my `c++` version, maybe i'm doing something wrong. Do you want me to open another issue?

**Comment by DethRaid** [comment]
Yeah, please open another GitHub issue for the compilation issues
